name: pull-requests

on:
  pull_request:
    branches: [ master ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"
            - run: npm ci
            - run: npm run build
            - run: npm run test
            - run: npm run lint
            - run: npm run spellcheck